# Generated by Django 2.2.5 on 2020-03-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Логотип рубрики')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Общая оценка')),
                ('friends_score', models.FloatField(blank=True, null=True, verbose_name='Оценка друзей')),
                ('user_score', models.FloatField(blank=True, null=True, verbose_name='Оценка пользователя')),
                ('info', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сведения')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='PBoard.Rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-published'],
            },
        ),
    ]
