# Generated by Django 2.2.5 on 2020-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='friends_score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.AlterField(
            model_name='post',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Сведения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='Pboard\\media\\posts', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='image',
            field=models.ImageField(null=True, upload_to='Pboard\\media\\rubric', verbose_name='Логотип рубрики'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
