# Generated by Django 2.2.5 on 2020-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBoard', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_authorship',
            field=models.BooleanField(default=True, verbose_name='Показывать автора'),
        ),
    ]
