"""
Django settings for shipaclub project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6cc!vdlg_5q(i@n)3w74vw)ti_&$m2k=_qb5l(^r+aac8c%t2b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup',
    'Mainpage.apps.MainpageConfig',
    'PBoard.apps.PboardConfig',
    'Accounts.apps.AccountsConfig',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.http.ConditionalGetMiddleware',  # для кэша
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Обязательно перед django.middleware.common.CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'shipaclub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':[
                'PBoard.templatetags.tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'shipaclub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# AUTH_USER_MODEL = "Accounts.AccUser"
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS =[
#     ('pboard','D:\\Projects\\Django\\shipaclub\\PBoard\\static'),
#     ('main','D:\\Projects\\Django\\shipaclub\\Mainpage\\static'),
# ]
# STATIC_ROOT = os.path.join(BASE_DIR, '/static')

MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'Desktop\\Projects\\Django\\shipaclub')

# Для взаимодействия с почтой

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'shipaclub@gmail.com'
EMAIL_HOST_PASSWORD = 'vn28082002'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# For django-REST
CORS_ORIGIN_ALLOW_ALL = True
# CORS_URLS_REGEX = r'^/api/.*$'

# Настройки отладки
# LOGGING = {
#     'version':1,
#     'disable_existing_logging':True,
#     'filters': {
#         'require_debug_false':{
#             '()':'django.utils.log.RequireDebugFalse',
#         },
#         'require_debug_true':{
#             '()':'django.utils.log.RequireDebugTrue',
#         },
#     },
#     'formatters': {
#         'simple': {
#             'format':'[%(asctime)s] %(levelname)s: %(message)s',
#             'datefmt':'%Y.%m.%d %H:%M:%S',
#         }
#     },
#     'handlers': {
#         'console_dev':{
#             'class':'logging.StreamHandler',
#             'formatter':'simple',
#             'filters':['require_debug_true'],
#         },
#         'console_prod':{
#             'class':'logging.StreamHandler',
#             'formatter':'simple',
#             'level':'ERROR',
#             'filters':['require_debug_false'],
#         },
#         'file':{
#             'class':'logging.handlers.RotatingFileHandler',
#             'filename':'d:/django-site.log',
#             'maxBytes':1048576,
#             'backupCount':10,
#             'formatter':'simple',
#         },
#     },
#     'loggers':{
#         'django':{
#             'handlers':['console_dev', 'console_prod'],
#         },
#         'django.server':{
#             'handlers':['file'],
#             'level':'INFO',
#             'propagate':True,
#         }
#     }

# }
